##Importing the Required Libraries

In [85]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##Importing the Dataset

In [94]:
data = pd.read_excel('Sales-Data-Analysis.xlsx')

In [95]:
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,NaN,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
3,NaN,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
4,NaN,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
...,...,...,...,...,...,...,...,...,...,...
257,NaN,10709,2022-12-28 00:00:00,Sides & Other,4.99,200.400802,Drive-thru,Gift Card,Walter Muller,Berlin
258,NaN,10710,2022-12-29 00:00:00,Burgers,12.99,754.426482,Drive-thru,Gift Card,Walter Muller,Berlin
259,NaN,10711,2022-12-29 00:00:00,Chicken Sandwiches,9.95,281.407035,Drive-thru,Gift Card,Walter Muller,Berlin
260,NaN,10712,2022-12-29 00:00:00,Fries,3.49,630.372493,Drive-thru,Gift Card,Walter Muller,Berlin
261,NaN,10713,2022-12-29 00:00:00,Beverages,2.95,677.966102,Drive-thru,Gift Card,Walter Muller,Berlin

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  262 non-null    object
 2   Unnamed: 2  262 non-null    object
 3   Unnamed: 3  262 non-null    object
 4   Unnamed: 4  262 non-null    object
 5   Unnamed: 5  262 non-null    object
 6   Unnamed: 6  262 non-null    object
 7   Unnamed: 7  262 non-null    object
 8   Unnamed: 8  262 non-null    object
 9   Unnamed: 9  262 non-null    object
dtypes: float64(1), object(9)
memory usage: 20.6+ KB

## Drop unwanted Columns

In [97]:
data.drop(columns="Unnamed: 0",inplace =True)

In [98]:
data.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
3,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
4,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon

## Changing the Column Name

In [99]:
data.columns

Index(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [101]:
data.columns= data.loc[0]

In [102]:
data.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
3,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
4,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon

## Drop Unwanted Rows

In [103]:
data.drop(0,inplace =True)

In [104]:
data

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
3,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
4,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
5,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
...,...,...,...,...,...,...,...,...,...
257,10709,2022-12-28 00:00:00,Sides & Other,4.99,200.400802,Drive-thru,Gift Card,Walter Muller,Berlin
258,10710,2022-12-29 00:00:00,Burgers,12.99,754.426482,Drive-thru,Gift Card,Walter Muller,Berlin
259,10711,2022-12-29 00:00:00,Chicken Sandwiches,9.95,281.407035,Drive-thru,Gift Card,Walter Muller,Berlin
260,10712,2022-12-29 00:00:00,Fries,3.49,630.372493,Drive-thru,Gift Card,Walter Muller,Berlin
261,10713,2022-12-29 00:00:00,Beverages,2.95,677.966102,Drive-thru,Gift Card,Walter Muller,Berlin

## Clean Manager Column

In [105]:
data.Manager.unique()

array(['Tom      Jackson', '       Pablo Perez', 'Joao    Silva',
       'Walter Muller', 'Remy    Monet', 'Remy Monet',
       '       Remy Monet', 'Remy     Monet', 'Pablo Perez',
       'Pablo   Perez', 'Pablo  Perez', 'Pablo    Perez', 'Joao Silva',
       'Tom Jackson'], dtype=object)

In [106]:
data.Manager.nunique()

14

In [107]:
data["Manager"]=data["Manager"].str.strip().str.replace(r'\s+',' ', regex= True)

In [108]:
data.head(20)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
2,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
3,10453,2022-11-07 00:00:00,Beverages,2.95,745.762712,Online,Gift Card,Pablo Perez,Madrid
4,10454,2022-11-07 00:00:00,Sides & Other,4.99,200.400802,In-store,Gift Card,Joao Silva,Lisbon
5,10455,2022-11-08 00:00:00,Burgers,12.99,569.668976,In-store,Credit Card,Walter Muller,Berlin
6,10456,2022-11-08 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Walter Muller,Berlin
7,10457,2022-11-08 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Remy Monet,Paris
8,10459,2022-11-08 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Walter Muller,Berlin
9,10460,2022-11-09 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Remy Monet,Paris
10,10461,2022-11-09 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Remy Monet,Paris
11,10462,2022-11-09 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Remy Monet,Paris
12,10463,2022-11-09 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Remy Monet,Paris
13,10464,2022-11-09 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Remy Monet,Paris
14,10465,2022-11-10 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Pablo Perez,Madrid
15,10466,2022-11-10 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Pablo Perez,Madrid
16,10467,2022-11-10 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Pablo Perez,Madrid
17,10467,2022-11-10 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Pablo Perez,Madrid
18,10468,2022-11-10 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Pablo Perez,Madrid
19,10470,2022-11-11 00:00:00,Burgers,12.99,554.272517,In-store,Credit Card,Pablo Perez,Madrid
20,10471,2022-11-11 00:00:00,Chicken Sandwiches,9.95,201.005025,In-store,Credit Card,Pablo Perez,Madrid

In [109]:
data["Manager"].nunique()

5

## Remove the Duplicate Records

In [110]:
data.describe()

/tmp/ipykernel_14095/3175101911.py:1: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  data.describe()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
count,261,261,261,261.00,261.000000,261,261,261,261
unique,254,53,5,10.00,29.000000,3,3,5,5
top,10452,2022-11-13 00:00:00,Fries,3.49,200.400802,Online,Credit Card,Joao Silva,Lisbon
freq,2,7,53,52.00,50.000000,108,126,78,78

In [111]:
data[data.duplicated()]

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
2,10452,2022-11-07 00:00:00,Fries,3.49,573.065903,Online,Gift Card,Tom Jackson,London
17,10467,2022-11-10 00:00:00,Fries,3.49,573.065903,In-store,Credit Card,Pablo Perez,Madrid
28,10478,2022-11-12 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Pablo Perez,Madrid
87,10536,2022-11-24 00:00:00,Chicken Sandwiches,9.95,201.005025,Drive-thru,Credit Card,Pablo Perez,Madrid

In [112]:
data.drop_duplicates(inplace=True)

In [113]:
data.describe()

/tmp/ipykernel_14095/3175101911.py:1: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  data.describe()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
count,257,257,257,257.00,257.000000,257,257,257,257
unique,254,53,5,10.00,29.000000,3,3,5,5
top,10484,2022-11-13 00:00:00,Burgers,12.99,200.400802,Online,Credit Card,Joao Silva,Lisbon
freq,2,7,53,52.00,50.000000,107,123,78,78

In [114]:
data[data["Order ID"].duplicated()]

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
65,10483,2022-11-13 00:00:00,Beverages,33.92,677.966102,In-store,Credit Card,Joao Silva,Lisbon
67,10484,2022-11-13 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Joao Silva,Lisbon
69,10485,2022-11-14 00:00:00,Burgers,112.99,523.4796,In-store,Credit Card,Joao Silva,Lisbon

## Duplicate by Outliers

In [115]:
data[data["Order ID"]== 10483]

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
64,10483,2022-11-13 00:00:00,Beverages,2.95,677.966102,In-store,Credit Card,Joao Silva,Lisbon
65,10483,2022-11-13 00:00:00,Beverages,33.92,677.966102,In-store,Credit Card,Joao Silva,Lisbon

In [116]:
data[data["Order ID"]== 10484]

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
66,10484,2022-11-13 00:00:00,Sides & Other,44.99,200.400802,In-store,Credit Card,Joao Silva,Lisbon
67,10484,2022-11-13 00:00:00,Sides & Other,4.99,200.400802,In-store,Credit Card,Joao Silva,Lisbon

In [117]:
data[data["Order ID"]== 10485]

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
68,10485,2022-11-14 00:00:00,Burgers,12.99,523.4796,In-store,Credit Card,Joao Silva,Lisbon
69,10485,2022-11-14 00:00:00,Burgers,112.99,523.4796,In-store,Credit Card,Joao Silva,Lisbon

In [118]:
data.drop([65,66,69], inplace= True)

In [119]:
data.describe()

/tmp/ipykernel_14095/3175101911.py:1: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  data.describe()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
count,254,254,254,254.00,254.000000,254,254,254,254
unique,254,53,5,7.00,29.000000,3,3,5,5
top,10452,2022-11-09 00:00:00,Chicken Sandwiches,12.99,200.400802,Online,Credit Card,Tom Jackson,London
freq,1,5,52,52.00,49.000000,107,120,75,75

## Converting the DataTypes

In [120]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254 entries, 1 to 261
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    object
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    object
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: object(9)
memory usage: 19.8+ KB

In [121]:
data.Quantity=data.Quantity.astype(float)

In [122]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254 entries, 1 to 261
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    object
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    object
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: float64(1), object(8)
memory usage: 19.8+ KB

In [123]:
data.Quantity=data.Quantity.round()

In [124]:
data.Quantity

1      573.0
3      746.0
4      200.0
5      570.0
6      201.0
       ...
257    200.0
258    754.0
259    281.0
260    630.0
261    678.0
Name: Quantity, Length: 254, dtype: float64

In [125]:
data.Quantity=data.Quantity.astype(int)

In [126]:
data.Quantity

1      573
3      746
4      200
5      570
6      201
      ...
257    200
258    754
259    281
260    630
261    678
Name: Quantity, Length: 254, dtype: int64

In [127]:
data['Order ID']=data['Order ID'].astype(int)
data['Price']= data['Price'].astype(float)

In [128]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254 entries, 1 to 261
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    int64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 19.8+ KB

## Convert to Date Format

In [129]:
data['Date']= pd.to_datetime(data['Date'])

In [130]:
data['Date']

1     2022-11-07
3     2022-11-07
4     2022-11-07
5     2022-11-08
6     2022-11-08
         ...
257   2022-12-28
258   2022-12-29
259   2022-12-29
260   2022-12-29
261   2022-12-29
Name: Date, Length: 254, dtype: datetime64[ns]

In [131]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254 entries, 1 to 261
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    datetime64[ns]
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    int64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 19.8+ KB

In [132]:
data

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
1,10452,2022-11-07,Fries,3.49,573,Online,Gift Card,Tom Jackson,London
3,10453,2022-11-07,Beverages,2.95,746,Online,Gift Card,Pablo Perez,Madrid
4,10454,2022-11-07,Sides & Other,4.99,200,In-store,Gift Card,Joao Silva,Lisbon
5,10455,2022-11-08,Burgers,12.99,570,In-store,Credit Card,Walter Muller,Berlin
6,10456,2022-11-08,Chicken Sandwiches,9.95,201,In-store,Credit Card,Walter Muller,Berlin
...,...,...,...,...,...,...,...,...,...
257,10709,2022-12-28,Sides & Other,4.99,200,Drive-thru,Gift Card,Walter Muller,Berlin
258,10710,2022-12-29,Burgers,12.99,754,Drive-thru,Gift Card,Walter Muller,Berlin
259,10711,2022-12-29,Chicken Sandwiches,9.95,281,Drive-thru,Gift Card,Walter Muller,Berlin
260,10712,2022-12-29,Fries,3.49,630,Drive-thru,Gift Card,Walter Muller,Berlin
261,10713,2022-12-29,Beverages,2.95,678,Drive-thru,Gift Card,Walter Muller,Berlin